//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityDoor.Tests.SecurityWeb {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://microsoft.com/samples/wf4/", ConfigurationName="SecurityWeb.ISecurityDoorService")]
    public interface ISecurityDoorService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://microsoft.com/samples/wf4/ISecurityDoorService/NotifyDoorStatus")]
        void NotifyDoorStatus(int RoomNumber, bool IsOpen, bool IsLocked);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/samples/wf4/ISecurityDoorService/AuthorizeKey", ReplyAction="http://microsoft.com/samples/wf4/ISecurityDoorService/AuthorizeKeyResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Authorized")]
        SecurityDoor.Contracts.AuthorizeResponse AuthorizeKey(int RoomNumber, System.Guid CardKey, System.TimeSpan Timeout, int IntrusionThreshold);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/samples/wf4/ISecurityDoorService/DoorReset", ReplyAction="http://microsoft.com/samples/wf4/ISecurityDoorService/DoorResetResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Authorized")]
        SecurityDoor.Contracts.AuthorizeResponse DoorReset(int RoomNumber, System.Guid CardKey, System.TimeSpan Timeout, int IntrusionThreshold);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISecurityDoorServiceChannel : SecurityDoor.Tests.SecurityWeb.ISecurityDoorService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SecurityDoorServiceClient : System.ServiceModel.ClientBase<SecurityDoor.Tests.SecurityWeb.ISecurityDoorService>, SecurityDoor.Tests.SecurityWeb.ISecurityDoorService {
        
        public SecurityDoorServiceClient() {
        }
        
        public SecurityDoorServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SecurityDoorServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecurityDoorServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecurityDoorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void NotifyDoorStatus(int RoomNumber, bool IsOpen, bool IsLocked) {
            base.Channel.NotifyDoorStatus(RoomNumber, IsOpen, IsLocked);
        }
        
        public SecurityDoor.Contracts.AuthorizeResponse AuthorizeKey(int RoomNumber, System.Guid CardKey, System.TimeSpan Timeout, int IntrusionThreshold) {
            return base.Channel.AuthorizeKey(RoomNumber, CardKey, Timeout, IntrusionThreshold);
        }
        
        public SecurityDoor.Contracts.AuthorizeResponse DoorReset(int RoomNumber, System.Guid CardKey, System.TimeSpan Timeout, int IntrusionThreshold) {
            return base.Channel.DoorReset(RoomNumber, CardKey, Timeout, IntrusionThreshold);
        }
    }
}
